# Generated by Django 4.1 on 2022-10-27 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("player", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tracksmodel",
            name="album_id",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="genre_tracks",
                to="player.albumsmodel",
            ),
        ),
    ]
