# Generated by Django 4.1 on 2022-11-08 08:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albumsmodel',
            name='album_releaseDate',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 11, 8, 8, 28, 21, 77314, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='artistsmodel',
            name='artist_releaseDate',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 11, 8, 8, 28, 21, 77502, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='tracksmodel',
            name='track_releaseDate',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 11, 8, 8, 28, 21, 77314, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
