# Generated by Django 4.1 on 2022-09-21 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='albumsmodel',
            name='album_price',
            field=models.IntegerField(blank=True, default=40),
        ),
        migrations.AddField(
            model_name='tracksmodel',
            name='track_price',
            field=models.IntegerField(blank=True, default=5),
        ),
    ]
