# Generated by Django 4.1 on 2022-10-27 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("player", "0002_alter_tracksmodel_album_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tracksmodel",
            name="album_id",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="trackasalbum",
                related_query_name="trackasalbumquery",
                to="player.albumsmodel",
            ),
        ),
        migrations.AlterField(
            model_name="tracksmodel",
            name="genre_id",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="genre_tracks",
                related_query_name="genre_tracks",
                to="player.genresmodel",
            ),
        ),
    ]
