# Generated by Django 4.1.4 on 2023-01-23 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracksmodel',
            name='artist_featuring',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
