# Generated by Django 4.1.4 on 2023-01-27 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tracksmodel',
            name='artist_featuring',
        ),
    ]
