# Generated by Django 4.1.4 on 2023-02-01 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_remove_tracksmodel_artist_featuring'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlbumDetailModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('privilege', models.CharField(blank=True, max_length=256, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('album_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='music.albumsmodel')),
                ('artist_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.artistsmodel')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
