# Generated by Django 4.1.4 on 2023-02-02 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_albumdetailmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='TracksViewCount',
            fields=[
                ('track_id', models.IntegerField(blank=True, primary_key=True, serialize=False)),
                ('track_viewcount', models.IntegerField(blank=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['track_id'],
            },
        ),
        migrations.AlterModelOptions(
            name='purchasedtracksmodel',
            options={'ordering': ['track_id']},
        ),
        migrations.RemoveField(
            model_name='purchasedtracksmodel',
            name='id',
        ),
        migrations.AlterField(
            model_name='purchasedtracksmodel',
            name='track_id',
            field=models.IntegerField(blank=True, primary_key=True, serialize=False),
        ),
    ]
