name: Trigger auto deployment for music-service

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ azure ]
    paths:
    - '**'
    - '.github/workflows/music-service-AutoDeployTrigger-96c3454d-157f-40aa-9d36-bc4471ce0544.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: zemacontainerregistry.azurecr.io
          username: ${{ secrets.MUSICSERVICE_REGISTRY_USERNAME }}
          password: ${{ secrets.MUSICSERVICE_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: zemacontainerregistry.azurecr.io/music-service:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.MUSICSERVICE_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n music-service -g Development --server zemacontainerregistry.azurecr.io --username  ${{ secrets.MUSICSERVICE_REGISTRY_USERNAME }} --password ${{ secrets.MUSICSERVICE_REGISTRY_PASSWORD }}
            az containerapp update -n music-service -g Development --image zemacontainerregistry.azurecr.io/music-service:${{ github.sha }}
